import { useState } from "react";

export const cosas = [
  "Tus ojitos",
  "Tus ojitos achinados",
  "Tu sonrisa",
  "Tus dientes",
  "Tus mofletes",
  "Tu nariz",
  "Tu voz",
  "Tu forma de amarme",
  "Cómo te llevas con tu familia",
  "Cómo te preocupas por mí",
  "Tus besitos",
  "Tus te quiero",
  "La forma en la que me miras en llamada",
  "Me haces sentirme muy amado",
  "Lo feliz que me haces",
  "Lo agusto que estoy contigo",
  "Lo rápido que pasa el tiempo contigo",
  "Tu belleza",
  "Eres la niña que siempre soñé",
  "Tus labios",
  "La forma en que hablas de nuestro futuro",
  "Nos queremos casar",
  "Tu sentido del humor",
  "Puedo confiar en ti",
  "Tus chistes",
  "ERES LA MEJOR AMOR",
  "Lo mona que eres cuando me hablas ñoño",
  "La sonrisa que te sale después de que te digo que te quiero",
  "La forma en la que me haces sonreír con simplemente un te amo",
  "Cuando me envías reels sobre cómo te sientes conmigo 💜💜💜",
  "Lo hermosa y bella que te ves siempre",
  "Podemos hablar de cualquier cosa",
  "Tenemos los mismos gustos",
  "Me encanta tu risa",
  "Tus muslos",
  "La forma en la que te expresas cuánto me amas aunque te cuesta 💜💜💜",
  "Mi vida ha mejorado gracias a ti",
  "Que eres muy muy muy lindaaaaaaa mi bb 💜💜💜",
  "Cuando me dices mi bb 💜",
  "Cuando estoy cansado tú eres mi descanso",
  "Me haces felices los días solo con darme los buenos días",
  "Que seas mi mujer, mi novia, mi pareja 💜",
  "Todas las canciones que me has dedicado: Muchas caricias, Te como la cara, No vendo humo, Deseándote, Be my baby, Cuenta conmigo y más 💜💜💜",
  "Me elegiste a mí",
  "Le hablas a la gente de mí 😭💜",
  "Que seas taaaaan mona y tan cariñosa",
  "Me encanta tu forma de hablar",
  "Tu acento",
  "Eres todo lo que quise",
  "Eres perfecta amor 💜",
  "Tu lado ñoño y cariñoso me encanta 😩💜",
  "Uso palabras de tu vocabulario",
  "Nunca me pides nada material y quiero darte todo",
  "Te quiero tanto que te voy a escribir un libro 💜💜💜🥰",
  "No fumas",
  "Sabes bailar (yo no sé, pero me enseñas cariño)",
  "Tu nombre 😩",
  "Mi negrita 💜💜💜",
  "Nuestros hijos serán super guapos",
  "Cómo vistes",
  "Me gusta cuando me cuentas todo 💜",
  "ERES MÍA SOLAMENTE MÍA",
  "Y YO TUYO",
  "Eres la perfección, mi novia es perfecta, todo lo que quise 💜",
  "Mismos gustos 😏",
  "Me respetas muchísimo 💜",
  "Me gusta mucho el amor que me has provocado en ti 💜",
  "Me dijiste el primer te quiero 💜💜💜💜",
  "Te amo mi negrita hermosa 💜",
  "SOÑASTE CONMIGO 😭😭😭💜💜💜💜",
  "Veo tu carita, tu sonrisa cuando cierro los ojos 💜",
  "Me encanta llamarte",
  "Estoy super agusto contigo",
  "Nos vamos a casar",
  "PORQUE ERES TAN HERMOSA MI NEGRA BELLA 😭😭😭💜💜💜",
  "Me encanta que me valores y me respetes",
  "Tu gusto musical",
  "No en serio, eres perfecta, es que eres lo que siempre quise 💜",
  "Te amo, me haces super feliz",
  "Llegaste cuando menos lo esperaba",
  "Tu pelo 😩",
  "Tu pelo suelto 😩",
  "La manera en la que me miras en la videollamada 💜",
  "Me quedo sin palabras para decirte cuánto te amo, por eso te escribo el libro",
  "Me encanta cómo me haces reír aún cuando tengo malos días",
  "Eres tú, no quiero a nadie más 💜",
  "Me haces ser mejor persona 💜",
  "Cuando me dijiste que desde que me conoces todo ha ido a mejor 😭💜",
  "Lo preciosa que eres, cada foto que tengo tuya las miro antes de dormir y les doy un besito",
  "Podemos hablar muchas cosas, es que eres perfecta 😭💜😩",
  "Te gustan mis gemidos 😳",
  "La forma en la que me haces super ñoño y cursi 💜",
  "La forma en la que me cuidas cuando estoy malito 🥺",
  "Sabes lo mucho que te quiero y lo enamorado que estoy por ti 💜",
  "Lo lista que eres, te hace aún más increíble 💜",
  "Lo mucho que te esfuerzas por conseguir entrar en lo que quieres. Lo vas a lograr, te voy a apoyar en todo 💜",
  "Formas parte de mi vida 💜",
  "Nunca me canso de hablar contigo",
  "MI NOVIA 💜",
  "Te voy a amar por siempre, eres mi niña, mi negrita, la mujer que más amo...",
  "Cuando haces algún plan y me dices 'ojalá estuvieses aquí'",
  "Cuando me dices mi bb, mi marido, mi novio, mi blanquito 😩💜",
  "Me gusta hasta la forma en que me regañas",
  "La forma en que me miras 💜",
  "Tu reacción a las notas que te escribo",
  "Me haces sentir único y especial",
  "Me inspiras a mejorar cada día 💜",
  "Me gusta alegrarte los días",
  "La confianza que tengo en ti 💜",
  "Lo muy enamorados que estamos el uno del otro",
  "Me haces llorar de felicidad por tenerte a mi lado 💜",
  "Mi madre está super feliz y orgullosa de que seas mi pareja 💜",
  "Lo bonitos que quedan tus ojos en la pulsera que me va a llegar",
  "Eres mi lugar de descanso, donde quiero estar cuando no tengo batería social",
  "Lo muy linda, hermosa y perfecta que eres 💜",
  "Lo bien que hablas de tus padres",
  "La tranquilidad que me haces sentir 💜",
  "Estoy obsesionado contigo",
  "Solo tienes ojos para mí 💜",
  "Que nuestro color sea el morado 💜",
  "De solo pensar en ti me sale una sonrisita tonta",
  "Cuando me dices lo mucho que me quieres",
  "La sonrisa y los ojos achinados que se te quedan después de que te lea una nota",
  "Lo increíble que eres",
  "Quieres jugar al Minecraft conmigo 😩💜",
  "Te chupo amor, eres hermosa 😳",
  "Aún cuando estás dormida, no paro de pensar en ti 💜",
  "Te amo cariño 💜",
  "Todas las canciones de amor me recuerdan a ti 💜",
  "ME DEDICAS CANCIONES 😭💜",
  "Te quiero hacer mimitos 💜🥺",
  "Cuando me das los buenos días sin yo aún haberme levantado 😭💜",
  "Me haces sentir super especial y único 💜",
  "No sé qué poner en esta pero de todo lo que escribí antes se me sale una lágrima 💜",
  "TE HAS COMPRADO UN ANILLO CON LA R 💜😭",
  "Lo del anillo es que te amoooooo",
  "Quieres siempre lo mejor para mí 💜",
  "La forma en la que reaccionas a los reels que te mando 💜",
  "Tu voz diciéndome 'te quiero' y 'te amo' 💜",
  "Cuando me dices un 'te quiero' en llamada y te sale la sonrisilla 😩💜",
  "Lo orgulloso que estoy de ti 💜",
  "Cuando me dices que vaya contigo a abrazarte y darte besitos 🥺💜",
  "Cuando me dices 'chi' 😩💜",
  "Mi amor 💜",
  "Cuando te leí la primera nota en llamada y te costó no llorar 💜😭",
  "Cuando me mandas tiktoks sobre planes o de enamorada 😭💜",
  "Tienes mi corazón, es tuyo, eres el amor de mi vida 💜",
  "Cuando me dices 'mi marido' 😩💜",
  "Lo mucho que quieres casarte conmigo 💜",
  "Aún así continuaría diciendo más cosas que me encantan de ti... Te amo 💜",
];


export default function Cosas() {
  const [indice, setIndice] = useState(0);

  const siguiente = () => {
    setIndice((prev) => (prev + 1) % cosas.length);
  };

  return (
    <div className="max-w-md mx-auto my-10 bg-white p-6 rounded-xl shadow-lg text-center">
      <h2 className="text-2xl font-bold text-purple-600 mb-4">150 cosas que amo de ti💜</h2>
      <p className="text-lg text-gray-700 mb-4 min-h-[80px] transition-all duration-300 ease-in-out">
        {cosas[indice]}
      </p>
      <button
        onClick={siguiente}
        className="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-700 transition"
      >
        Ver la siguiente  →
      </button>
      <p className="text-sm mt-2 text-gray-500">{indice + 1} / {cosas.length}</p>
    </div>
  );
}
